export type ImpactLevel = "High" | "Medium" | "Low";

export const TWEAK_IMPACTS: Record<string, ImpactLevel> = {
  // High — users notice a clear real-world difference
  "Disable Mouse Acceleration":                    "High",
  "Disable Multiplane Overlay (MPO)":              "High",
  "Maximum Priority for Games":                    "High",
  "System Responsiveness & Network Throttling":    "High",
  "Enable Hardware Accelerated GPU Scheduling (HAGS)": "High",
  "Disable SuperFetch / SysMain":                  "High",
  "Disable Windows File Indexing":                 "High",
  "Optimize Visual Effects for Performance":       "High",
  "Disable Power Throttling":                      "High",
  "Keep Kernel & Drivers in RAM":                  "High",
  "Disable Memory Compression":                    "High",
  "Disable Connected Telemetry (DiagTrack)":       "High",
  "Unlock Reserved Network Bandwidth":             "High",
  "Disable Delivery Optimization Service":         "High",
  "Disable Virtualization-Based Security (VBS)":   "High",

  // Medium — measurable improvement, may not be immediately obvious
  "Disable Background UWP Apps":                   "Medium",
  "Keep All CPU Cores Active (Unpark Cores)":      "Medium",
  "Win32 Priority Separation":                     "Medium",
  "Disable GameBar":                               "Medium",
  "Disable GameBar Background Recording":          "Medium",
  "Enable Game Mode":                              "Medium",
  "Disable Cortana":                               "Medium",
  "Disable Startup Program Delay":                 "Medium",
  "Disable Hibernation":                           "Medium",
  "Disable Full Screen Optimizations":             "Medium",
  "Optimize for Windowed & Borderless Games":      "Medium",
  "Disable Windows TCP Auto-Tuning":               "Medium",
  "Disable Windows Automatic Maintenance":         "Medium",
  "Fortnite Process High Priority":                "Medium",
  "Disable Xbox Core Services":                    "Medium",
  "Disable Web Search in Windows Search":          "Medium",
  "Instant Menu Response (Zero Delay)":            "Medium",
  "Disable NTFS Access Timestamps":                "Medium",
  "Auto-End Unresponsive Programs":                "Medium",
  "Disable Scheduled Disk Defragmentation":        "Medium",
  "Svchost Process Isolation":                     "Medium",
  "Optimize Boot Configuration":                   "Medium",
  "Disable Notification Center":                   "Medium",
  "Network Optimization":                          "High",
  "Disable USB Selective Suspend":                 "Medium",
  "Disable Windows Error Reporting":               "Medium",
  "Disable Application Compatibility Telemetry":   "Medium",
  "Disable Windows Activity History":              "Medium",
  "Disable Windows Content Delivery Manager":      "Medium",
  "Raise System Timer IRQ Priority":               "Medium",
  "Foreground Application Priority Lock Timeout":  "Low",
  "Disable Print Spooler":                         "Medium",
  "Disable Windows Copilot AI Sidebar":            "Medium",
  "Disable Auto-Restart After Windows Updates":    "Medium",

  // Low — subtle, background improvements
  "Prefer IPv4 over IPv6":                         "Low",
  "Disable Phone Link & Mobile Sync":              "Low",
  "Disable 8.3 Short File Names":                  "Low",
  "Disable Taskbar & Menu Animations":             "Low",
  "Reduce Taskbar Preview Delay":                  "Low",
  "Disable AutoPlay for External Devices":         "Low",
  "Reduce Keyboard Input Delay":                   "Low",
  "Disable Transparency Effects":                  "Low",
  "Disable Tile Notification System":              "Low",
  "Disable Windows Advertising ID":                "Low",
  "Disable Clipboard History Collection":          "Low",
  "Disable Windows 11 Widgets Panel":              "Low",
  "Disable Phone Link App":                        "Low",
};

export function getImpact(title: string): ImpactLevel | null {
  return TWEAK_IMPACTS[title] ?? null;
}
